### ISSUE TITLE
iOS example app images not loading (iOS 14.1 Xcode 12)

### ISSUE THREAD

**Issue by dwshiver** [pxblue/react-native-workflows#32]
When running the example app on an iOS simulator (iPhone 12 - iOS 14) in Xcode 12, the main logo does not appear to load.

<img width="560" alt="Screen Shot 2020-11-10 at 4 03 27 PM" src="https://user-images.githubusercontent.com/26386179/98740029-ff823f00-236f-11eb-93c3-9cf8df95c36d.png">

Here are related issues in the react-native repo:

https://github.com/facebook/react-native/issues/29369
https://github.com/facebook/react-native/issues/29279 - one line fix in pod dependency to build locally fine
https://github.com/facebook/react-native/issues/29237

Appears to be fixed in v0.63.2 https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0632

**Comment by joebochill** [comment]
Let's update this example to use the latest version of RN and see if that fixes this. We will also need to update one of our machines to xCode 12 (seems like we are all still using 11) to confirm this.

We might also want to lump this in with the backlog item to update this example to use Swift for iOS instead of Objective C.
